disableConfigWatcher = false
logUntranslatedConfigurationWarnings = true
#Path to load default configs from, intended for setting global server configs for newly created worlds, but also works when recreating client and common configs.
defaultConfigsPath = "defaultconfigs"
